### PR TITLE
fix conversion_value in <noscript and easymarketing. delete symbols

### PR DESCRIPTION
**Pull request by jBangiev**

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hi @jBangiev,

You have to update the version number, the module is already at the version 0.4.0 (https://github.com/PrestaShop/easymarketing/commit/9c8ee6f075289f5666a4d77b80149be803687914) ;)

Regards

**Comment by CamSi** [comment]
Hi @alexsimple ,
Thanks for your commit. But please do not forget to write a short comment so that we can receive notifications about your commit!
Thanks a lot, 
Camille

**Comment by Quetzacoalt91** [comment]
Hi @jBangiev and @alexsimple,

Thanks, your PR has just been merged and the changes will be available from tomorrow.
I brought back the file config.xml, do not remove it for the next PR ;)

Best regards

**Comment by robg336699** [comment]
Hi Thomas,

could you merge that pull request please.

https://github.com/PrestaShop/easymarketing/pulls

Thanks,

Robert

-------------------------------------
Robert Gold
CTO

mail to: robert.gold@easymarketing.de
phone: +49.89.20.333.250
cell:  + 49.171.1909752

easymarketing AG
Adelgundenstraße 5b
80538 München

Niederlassung Nürnberg:
Frankenstraße 148 
90461 Nürnberg 

HRB: 127234, Amtsgericht Hamburg
Vorstand: Christian Hampp
Vorsitzender des Aufsichtsrates: Dr. Ulf Renzenbrink
USt-Id: DE288753744
www.easymarketing.de

Am 04.06.2015 um 11:25 schrieb Thomas N <notifications@github.com>:

**Pull request merged**
