### PR TITLE
fix price of product combination

### PR DESCRIPTION
**Pull request by alexsimple**

### CODE REVIEW

**Comment by alexsimple** [comment]
Hi !
Please accept this pull request.

**Comment by mickaelandrieu** [comment]
Hi @alexsimple,
as you can see, we cant merge as your branch has conflicts.
Please rebase from master branch, fix conflicts and we can start reviewing your contribution.

Mickaël

**Comment by mmoustai** [comment]
Hello @alexsimple 

You need to follow the PSR-2 coding standart and also correct the following errors that our validator show up. https://validator.prestashop.com

download 16

Have a great day,
Regards,

**Comment by alexsimple** [comment]
Hello 
Please accept this pull request.

**Pull request merged**
